### PR TITLE
fix: add types

### PR DESCRIPTION
**Pull request by Spencer17x**
Now the npm package cannot read the type, this pr fixes the problem.

### CODE REVIEW

**Comment by noname0310** [comment]
I just checked, but this is not a package.json problem, it's just a problem because I didn't apply path transform to the build I'll take care of it now.

**Comment by Spencer17x** [comment]
So you don't think this pr will fix the problem？

**Comment by noname0310** [comment]
Yes, that's right. The version that solved the problem has just been deployed Please update it

**Comment by Spencer17x** [comment]
Or I don't think you understand what I mean.
What I mean is that the npm package babylon-mmd cannot be used in ts environment now because you did not specify the path to d.ts in package.json.
Now this pr mainly fixes this problem

**Comment by noname0310** [comment]
I'll close it if there's no problem. Thank you for the information.

**Pull request closed without merging**
